[project]
name = "blaze4harbor"
version = "0.1.0"
description = "A thin wrapper CLI to run harbor and show result directories more easily."
requires-python = ">=3.12"
dependencies = [
    "harbor>=0.1.18",
    "google-cloud-storage>=2.18.0",
    "google-cloud-bigquery>=3.0.0",
]
